import { RepoFile, UnpackerType, PackStats } from "../types";
import { generateAsciiTree } from "./treeGenerator";

const SEPARATOR_HEAVY = "=".repeat(80);
const SEPARATOR_LIGHT = "-".repeat(80);

export function generateUnpackerScript(
  type: UnpackerType,
  repoName: string,
  timestamp: string,
  fileCount: number,
  lineCount: number
): string {
  if (type === "node") {
    return `#!/usr/bin/env node
/**
 * ==============================================================================
 * REPO CONTAINER: ${repoName}
 * Generated by RepoPack on: ${timestamp}
 * Files: ${fileCount} | Total Lines: ${lineCount}
 * ==============================================================================
 * HOW TO DUMP THIS CONTAINER BACK INTO FILES:
 *   Option 1 (Direct Execution with Node.js):
 *     node <this_file> [target_directory]
 *     Example: node repo_container.txt ./my_app
 * ==============================================================================
 */
const fs = require('fs');
const path = require('path');

const targetDir = process.argv[2] && !process.argv[2].endsWith('.txt') && !process.argv[2].endsWith('.js')
  ? process.argv[2]
  : '.';

const scriptPath = process.argv[1];
const content = fs.readFileSync(scriptPath, 'utf8');

const regex = /^={80}\\r?\\nFILE:\\s*([^\\r\\n]+)\\r?\\n(?:LINES:[^\\r\\n]*\\r?\\n)?={80}\\r?\\n([\\s\\S]*?)\\r?\\n-{80}\\r?\\nEND FILE:\\s*\\1\\r?\\n={80}/gm;

let match;
let count = 0;
console.log(\`[*] Extracting repository container into: \${targetDir}...\`);

while ((match = regex.exec(content)) !== null) {
  const relPath = match[1].trim();
  const fileData = match[2];
  const fullPath = path.join(targetDir, relPath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, fileData, 'utf8');
  console.log(\`  [CREATED] \${relPath}\`);
  count++;
}

console.log(\`\\n[OK] Successfully restored \${count} files into '\${targetDir}'.\`);
process.exit(0);
`;
  }

  // Universal Bash / Python self-extracting header
  return `#!/usr/bin/env bash
# ==============================================================================
# REPO CONTAINER: ${repoName}
# Generated by RepoPack on: ${timestamp}
# Files: ${fileCount} | Total Lines: ${lineCount}
# ==============================================================================
# SELF-INSTRUCTIONS TO DUMP THIS CONTAINER BACK INTO FILES:
#
# Method 1 (Direct Execution with Bash on macOS / Linux / WSL / Git Bash):
#     bash <this_file> [target_directory]
#     Examples:
#         bash repo_container.txt
#         bash repo_container.txt ./my_restored_repo
#
# Method 2 (Using Python 3):
#     python3 - < <this_file>
#
# Method 3 (Built-in Web Unpacker):
#     Drop or paste this text file into RepoPack web tool to view or export as .ZIP!
# ==============================================================================

if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ] || [ -n "$SH_VERSION" ] || [ -f "$0" ]; then
    python3 -c '
import sys, os, re

src = sys.argv[1]
dest = sys.argv[2] if len(sys.argv) > 2 else "."

if src == "-" or not os.path.isfile(src):
    text = sys.stdin.read()
else:
    with open(src, "r", encoding="utf-8", errors="replace") as f:
        text = f.read()

pattern = re.compile(
    r"^={80}\\r?\\nFILE:\\s*([^\\r\\n]+)\\r?\\n(?:LINES:[^\\r\\n]*\\r?\\n)?={80}\\r?\\n([\\s\\S]*?)\\r?\\n-{80}\\r?\\nEND FILE:\\s*\\1\\r?\\n={80}",
    re.M
)

matches = list(pattern.finditer(text))
if not matches:
    print("[-] No marked files found in container.")
    sys.exit(1)

print(f"[*] Restoring {len(matches)} files into \x27{dest}\x27...")
for m in matches:
    rel = m.group(1).strip()
    dest_path = os.path.join(dest, rel)
    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    with open(dest_path, "w", encoding="utf-8") as out:
        out.write(m.group(2))
    print(f"  + {rel}")

print(f"\\n[OK] Successfully restored {len(matches)} files into \x27{dest}\x27.")
' "$0" "\${1:-.}"
    exit 0
fi
`;
}

export function buildTextContainer(
  repoName: string,
  files: RepoFile[],
  unpackerType: UnpackerType = "python"
): {
  containerText: string;
  asciiTree: string;
  stats: PackStats;
} {
  const includedFiles = files.filter(
    (f) => f.status === "included" && f.isSelected !== false && f.content !== undefined
  );

  const skippedCount = files.length - includedFiles.length;
  const totalLines = includedFiles.reduce((acc, f) => acc + f.lines, 0);
  const totalBytes = includedFiles.reduce((acc, f) => acc + (f.content ? f.content.length : f.size), 0);

  // Generate ASCII tree for included files
  const filePaths = includedFiles.map((f) => f.path);
  const asciiTree = generateAsciiTree(filePaths);

  const timestamp = new Date().toISOString().replace("T", " ").substring(0, 19) + " UTC";

  // 1. Unpacker script at the very top
  const unpackerScript = generateUnpackerScript(
    unpackerType,
    repoName,
    timestamp,
    includedFiles.length,
    totalLines
  );

  // 2. Directory structure section
  const directorySection = [
    SEPARATOR_HEAVY,
    "REPOSITORY DIRECTORY STRUCTURE",
    SEPARATOR_HEAVY,
    asciiTree,
    SEPARATOR_HEAVY,
    "",
  ].join("\n");

  // 3. Line-for-line contents of every file with clear marked separations
  const fileBlocks: string[] = [];

  for (const file of includedFiles) {
    const content = file.content || "";
    const sizeStr = `${(file.size / 1024).toFixed(1)} KB (${file.size} bytes)`;
    const block = [
      SEPARATOR_HEAVY,
      `FILE: ${file.path}`,
      `LINES: ${file.lines} | SIZE: ${sizeStr}`,
      SEPARATOR_HEAVY,
      content,
      SEPARATOR_LIGHT,
      `END FILE: ${file.path}`,
      SEPARATOR_HEAVY,
    ].join("\n");
    fileBlocks.push(block);
  }

  const containerText = [
    unpackerScript.trim(),
    "",
    directorySection,
    fileBlocks.join("\n\n"),
    "",
    SEPARATOR_HEAVY,
    `END OF REPO CONTAINER: ${repoName} (${includedFiles.length} files restored)`,
    SEPARATOR_HEAVY,
  ].join("\n");

  // Approximate tokens: ~4 chars per token for code/text
  const estimatedTokens = Math.round(containerText.length / 4);

  return {
    containerText,
    asciiTree,
    stats: {
      totalScanned: files.length,
      includedCount: includedFiles.length,
      skippedCount,
      totalLines,
      totalBytes: containerText.length,
      estimatedTokens,
    },
  };
}
